app/models.py
import os
from flask import url_for
from flask_login import UserMixin
from flask_admin import form
from flask_admin.contrib.sqla import ModelView
from flask_sqlalchemy import SQLAlchemy
from markupsafe import Markup
from sqlalchemy.orm import relationship
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32), unique=True, nullable=False)
    email = db.Column(db.String(32), unique=True, nullable=False)
    phone = db.Column(db.String, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == "admin"

    def __repr__(self):
        return f'<User {self.id} - {self.name}>'


class ProductGroup(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    group_name = db.Column(db.String(32), unique=True, nullable=False)
    description = db.Column(db.Text, nullable=True)
    image = db.Column(db.Unicode(128), nullable=True)

    def __repr__(self):
        return f'ProductGroup {self.id} - {self.group_name}'


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    price = db.Column(db.Integer)
    count = db.Column(db.String)
    file_name = db.Column(db.String, nullable=True, default='Rectangle30.png')
    scientific_name = db.Column(db.String)
    # productgroup_id = db.Column(
    #     db.Integer,
    #     db.ForeignKey('productgroup.id', ondelete='CASCADE'),
    #     nullable=True,
    #     index=True
    # )
    # user_id = db.Column(
    #     db.Integer,
    #     db.ForeignKey('user.id', ondelete='CASCADE'),
    #     nullable=True,
    #     index=True
    # )

    # productgroup = relationship('ProductGroup', backref='products')
    # user = relationship('User', backref='products')

    def __repr__(self):
        return f'<Product {self.id} - {self.name}>'


class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    order_date = db.Column(db.DateTime)
    # user_id = db.Column(
    #     db.Integer,
    #     db.ForeignKey('user.id', ondelete='CASCADE'),
    #     nullable=True,
    #     index=True
    # )

    def __repr__(self):
        return f'<Cart {self.id}>'


cart_product = db.Table(
    "cart_product",
    db.Column("cart_id", db.Integer, db.ForeignKey("cart.id"), primary_key=True),
    db.Column("product_id", db.Integer, db.ForeignKey("product.id"), primary_key=True),
)


# class ProductModelView(ModelView):
#     def _list_thumbnail(view, context, model, name):
#         if not model.path:
#             return ""

#         filename = form.thumbgen_filename(model.path)
#         url = url_for('static', filename=filename)

#         return Markup(f'<img src="{url}">')

#     column_formatters = {"path": _list_thumbnail}

#     form_extra_fields = {
#         'image': form.ImageUploadField(
#             'Image',
#             base_path=os.path.join(os.path.dirname(__file__), 'static/img'),
#             thumbnail_size=(120, 120, True),
#         )
#     }

app/__init__.py
from flask import Flask
from flask_migrate import Migrate

from app.db import db
from app.models import db
from app.product.views import blueprint as prod_blueprint


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)
    migrate = Migrate(app, db)

    app.register_blueprint(prod_blueprint)

    return app

app/product/views.py
from flask import Blueprint, render_template, request

from app.models import Product


blueprint = Blueprint('product', __name__)  # url_prefix='/product'


@blueprint.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    title = 'Sukki.com'
    products = Product.query.order_by(Product.price.desc()).paginate(page=page, per_page=24)
    return render_template('product/catalog.html', title=title, products=products)


@blueprint.route('/productcard/<int:product_id>/')
def card_of_product(product_id):
    page = request.args.get('page', 1, type=int)
    product = Product.query.get_or_404(product_id)
    return render_template('product/product_card.html', product=product, page_num=page)


@blueprint.route('/echeveria/')
def echeveria():
    page = request.args.get('page', 1, type=int)
    products = Product.query.filter(Product.scientific_name == 'Echeveria').order_by(Product.price.desc()).paginate(page=page, per_page=24)
    return render_template('product/echeveria.html', products=products)


@blueprint.route('/haworthia/')
def haworthia():
    page = request.args.get('page', 1, type=int)
    products = Product.query.filter(Product.scientific_name == 'Haworthia').order_by(Product.price.desc()).paginate(page=page, per_page=24)
    return render_template('product/haworthia.html', products=products)


@blueprint.route('/sortbyprice/')
def sortbyprice():
    # page = request.args.get('page', 1, type=int)
    products = Product.query.order_by(Product.price.desc()).all()
    # result = list(map(int, products))
    print(type(products[1]))
    return render_template('product/sortpricetest.html', products=products)

app/templates/about_me.html
<section id="about_me" class="about pt-5 pb-5">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="text-center mb-3">Обо мне</h2>
        </div>
      </div>
      <div class="row align-item-center">
        <div class="col-12">
          <p class="description">
            Привет, меня зовут <strong>Вероника</strong>!<br /><br />
            Мне крайне интересно, кто заботится о своих растишках по ту
            сторону экрана. Если вы на этой страничке, то у нас с вами как
            минимум один общий интерес, и это прекрасный повод познакомиться
            поближе!</p>
          </div>
        <div class="col-xxl-7 col-xl-6 col-sm-12">
          <p class="description">
            Расскажу немного о себе.<br>По профессии и призванию я
            поглотитель вкусной еды и дигустатор изысканных напитков. Очень
            люблю спорт и стараюсь поддерживать активный образ жизни. Однажды
            в горах, на скалах, я впервые увидела как растут суккуленты и даже
            умудрилась привезти несколько штук домой. Они и по сей день
            отлично себя чувствуют на альпийской горке. <br> Тогда я ещё не думала о 
            коллекции, но случился карантин и вот я здесь!</p>
          </p>
        </div>
        <div class="col-xxl-5 col-xl-6 col-sm-12 mt-sm-3 mb-sm-3 text-center">
          <img
            src="{{url_for('static', filename='/img/rejule.png')}}"
            alt="photo of the founder"
            class="img-fluid"
          />
        </div>
      </div>
    </div>
  </section>

app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}" type="image/x-icon" />
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}" />
    <link rel="stylesheet" href="{{url_for('static', filename='css/fontello.css')}}" />
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&display=swap" rel="stylesheet"/>
    <title>{{ title }}</title>
  </head>
  <body>

    {% include "header.html" %}
    {% include "slider.html" %}

    {% block content %}

    {% endblock %}

    {% include "buy_instruction.html" %}
    {% include "about_me.html" %}
    {% include "contacts.html" %}

    {% if products.page == 1 %}
    <script>
      window.onscroll = function () {
        var scrolled = window.pageYOffset || document.documentElement.scrollTop; // Получаем положение скролла
        if (scrolled > 300) {
          // Если прокрутка больше 300px, то делаем блок видимым
          document.querySelector(".header-bg").style.opacity = "1";
        } else {
          // Если нет, то делаем его полупрозрачным
          document.querySelector(".header-bg").style.opacity = "0.5";
        }
      };
    </script>
    {% endif %}

    <script src="{{url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>
  </body>
</html>

app/templates/buy_instruction.html
<section id="buy_instruction" class="buy-instruction pt-5 pb-5">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="text-center mb-3">Как купить</h2>
        </div>
      </div>
      <div class="row align-item-center">
        <div class="col-6">
          <p class="description">После совершения заказа, дождитесь получения СМС-оповещения о том, 
          что ваш заказ готов к выдаче. Заказы которые состоят только из суккулентов или грунтов 
          собираются быстро, такой заказ возможно забрать день в день. 
          Заказы в которых присутствуют готовые композиции, горшки или подносы, могут собираться 
          дольше в связи с возможным отсутствием желаемой расцветки изделия. В таком случае на 
          выполнение заказа необходимо не менее 5 рабочих дней. Уточнить сроки готовности заказа 
          можно по почте, телефону или через соц.сети.
          </p>
        </div>
        <div class="col-xxl-5 col-xl-6 col-sm-12 mt-sm-3 mb-sm-3 text-center">
          <img
            src="{{url_for('static', filename='/img/Rectangle30.png')}}"
            alt="sukki-buy-image"
            class="img-fluid"
          />
        </div>
      </div>
    </div>
  </section>

app/templates/contacts.html
<section id="contacts" class="contact-me pt-5 pb-5">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="text-center mb-3">Контакты</h2>
        </div>
      </div>
      <div class="row align-item-center">
        <div class="col-lg-6 col-md-12 mt-md-3 mb-md-3 text-center">
          <img
            src="{{url_for('static', filename='/img/Rectangle31.png')}}"
            alt="sukki-buy-image"
            class="img-fluid"
          />
        </div>
        <div class="col-lg-6 col-md-12">
          <div class="text-center block-icon">
            <a href="https://instagram.com/_green.level_?r=nametag" target="_blank">
              <img src="{{url_for('static', filename='/img/insta-icon.png')}}" alt="insta-icon"><p>@_green.level_</p></a>
            <div class="line"></div>
            <a href="https://vk.com/serpiwomen" target="_blank">
              <img src="{{url_for('static', filename='/img/vkcom-icon.png')}}" alt="vkcom-icon"><p>https://vk.com/serpiwomen</p></a>
            <div class="line"></div>
            <a href="mailto:mallkavianka@yandex.ru?subject=Sukki.com_Вопрос о суккулентах" target="_blank">
              <img src="{{url_for('static', filename='/img/email-icon.png')}}" alt="email-icon"><p>mallkavianka@yandex.ru</p></a>
          </div>
        </div>
      </div>
    </div>
  </section>

app/templates/header.html
<header class="fixed-top header-bg">
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
          data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="#catalog">Каталог</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#buy_instruction">Как купить</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#about_me">Обо мне</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#contacts">Контакты</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>

app/templates/product/catalog.html
{% extends "base.html" %}

{% block content %}

<section id="catalog" class="catalog-all pt-5 pb-5">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="text-center mb-2">Каталог</h2>
        </div>
      </div>
    </div>
    <div class="container pb-5">

      <a href="{{ url_for('product.sortbyprice') }}">Сортировка</a>

      <div class="dropdown">
        <a class="btn btn-dark btn-lg dropdown-toggle"
        href="#" role="button" id="dropdownMenuLink"
        data-bs-toggle="dropdown" aria-expanded="false">
          Суккуленты
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><a class="dropdown-item" href="{{ url_for('product.echeveria') }}">Echeveria</a></li>
          <li><a class="dropdown-item" href="{{ url_for('product.haworthia') }}">Haworthia</a></li>
          <!-- <li><a class="dropdown-item" href="{{ url_for('product.index') }}">Сбросить фильтр</a></li> -->
        </ul>
      </div>
    </div>
    <div class="container">
      <div class="row row-cols-1 row-cols-lg-4 row-cols-md-2 g-4">
        {% for product in products %}
          <div class="col">
            <div class="card">
              <img src="{{ url_for('static', filename='/prod_image/'+product.file_name) }}" class="card-img-top" alt="{{ product.file_name }}">
              <h4 class="price"><strong>{{ product.price }} &#8381</strong></h4>
              <a href="" class="href">
                <img 
                src="{{url_for('static', filename='/img/add-to-cart.png')}}"
                class="add-to-cart" title="Добавить в корзину"
                alt="add-to-cart">
              </a>
              <a href="" class="href">
                <img 
                src="{{url_for('static', filename='/img/heart.png')}}"
                class="heart" title="Добавить в избранное"
                alt="heart">
              </a>
              <div class="card-body text-center">
                <a href="{{ url_for('product.card_of_product', product_id=product.id)}}" 
                target="_blank" title="Перейти на карточку товара"><strong>{{ product.name }}</strong>
                </a> 
              </div>
            </div>
          </div>
        {% endfor %}
      </div>

      <nav class="pt-5" aria-label="Page navigation example"></nav>
        <ul class="pagination justify-content-center">  
          {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=5, right_current=8) %}
            {% if page_num %}
              {% if products.page == page_num %}
                <li class="page-item me-2">
                  <a class="btn btn-info mb-4" href="{{ url_for('product.index', page=page_num) }}">{{ page_num }}</a></li>
              {% else %}
                <li class="page-item me-2">
                  <a class="btn btn-info-outline mb-4" href="{{ url_for('product.index', page=page_num) }}">{{ page_num }}</a>
                </li>
              {% endif %}
            {% else %}
            <li class="page-item me-2">...</li>
            {% endif %}
          {% endfor %}
        </ul>
      </nav>

    </div>
</section>

{% endblock %}

app/templates/product/echeveria.html
{% extends "base.html" %}

{% block content %}

<section id="catalog" class="catalog-all pt-5 pb-5">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="text-center mb-2">Каталог</h2>
        </div>
      </div>
    </div>
    <div class="container pb-5">
      <div class="dropdown">
        <a class="btn btn-dark btn-lg dropdown-toggle"
        href="#" role="button" id="dropdownMenuLink"
        data-bs-toggle="dropdown" aria-expanded="false">
          Суккуленты
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><a class="dropdown-item active" href="{{ url_for('product.echeveria') }}">Echeveria</a></li>
          <li><a class="dropdown-item" href="{{ url_for('product.haworthia') }}">Haworthia</a></li>
          <li><a class="dropdown-item" href="{{ url_for('product.index') }}">Сбросить фильтр</a></li>
        </ul>
      </div>
    </div>
    <div class="container">
      <div class="row row-cols-1 row-cols-lg-4 row-cols-md-2 g-4">
        {% for product in products %}
          <div class="col">
            <div class="card">
              <img src="{{ url_for('static', filename='/prod_image/'+product.file_name) }}" class="card-img-top" alt="{{ product.file_name }}">
              <h4 class="price"><strong>{{ product.price }} &#8381</strong></h4>
              <a href="" class="href">
                <img 
                src="{{url_for('static', filename='/img/add-to-cart.png')}}"
                class="add-to-cart" title="Добавить в корзину"
                alt="add-to-cart">
              </a>
              <a href="" class="href">
                <img 
                src="{{url_for('static', filename='/img/heart.png')}}"
                class="heart" title="Добавить в избранное"
                alt="heart">
              </a>
              <div class="card-body text-center">
                <a href="{{ url_for('product.card_of_product', product_id=product.id)}}" 
                target="_blank" title="Перейти на карточку товара"><strong>{{ product.name }}</strong>
                </a> 
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <nav class="pt-5" aria-label="Page navigation example"></nav>
      <ul class="pagination justify-content-center">  
        {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=5, right_current=8) %}
          {% if page_num %}
            {% if products.page == page_num %}
              <li class="page-item me-2">
                <a class="btn btn-info mb-4" href="{{ url_for('product.echeveria', page=page_num) }}">{{ page_num }}</a></li>
            {% else %}
              <li class="page-item me-2">
                <a class="btn btn-info-outline mb-4" href="{{ url_for('product.echeveria', page=page_num) }}">{{ page_num }}</a>
              </li>
            {% endif %}
          {% else %}
          <li class="page-item me-2">...</li>
          {% endif %}
        {% endfor %}
      </ul>
      </nav>
    </div>
</section>

{% endblock %}

app/templates/product/haworthia.html
{% extends "base.html" %}

{% block content %}

<section id="catalog" class="catalog-all pt-5 pb-5">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <h2 class="text-center mb-2">Каталог</h2>
        </div>
      </div>
    </div>
    <div class="container pb-5">
      <div class="dropdown">
        <a class="btn btn-dark btn-lg dropdown-toggle"
        href="#" role="button" id="dropdownMenuLink"
        data-bs-toggle="dropdown" aria-expanded="false">
          Суккуленты
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><a class="dropdown-item" href="{{ url_for('product.echeveria') }}">Echeveria</a></li>
          <li><a class="dropdown-item active" href="{{ url_for('product.haworthia') }}">Haworthia</a></li>
          <li><a class="dropdown-item" href="{{ url_for('product.index') }}">Сбросить фильтр</a></li>
        </ul>
      </div>
    </div>
    <div class="container">
      <div class="row row-cols-1 row-cols-lg-4 row-cols-md-2 g-4">
        {% for product in products %}
          <div class="col">
            <div class="card">
              <img src="{{ url_for('static', filename='/prod_image/'+product.file_name) }}" class="card-img-top" alt="{{ product.file_name }}">
              <h4 class="price"><strong>{{ product.price }} &#8381</strong></h4>
              <a href="" class="href">
                <img 
                src="{{url_for('static', filename='/img/add-to-cart.png')}}"
                class="add-to-cart" title="Добавить в корзину"
                alt="add-to-cart">
              </a>
              <a href="" class="href">
                <img 
                src="{{url_for('static', filename='/img/heart.png')}}"
                class="heart" title="Добавить в избранное"
                alt="heart">
              </a>
              <div class="card-body text-center">
                <a href="{{ url_for('product.card_of_product', product_id=product.id)}}" 
                target="_blank" title="Перейти на карточку товара"><strong>{{ product.name }}</strong>
                </a> 
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      <nav class="pt-5" aria-label="Page navigation example"></nav>
      <ul class="pagination justify-content-center">  
        {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=5, right_current=8) %}
          {% if page_num %}
            {% if products.page == page_num %}
              <li class="page-item me-2">
                <a class="btn btn-info mb-4" href="{{ url_for('product.haworthia', page=page_num) }}">{{ page_num }}</a></li>
            {% else %}
              <li class="page-item me-2">
                <a class="btn btn-info-outline mb-4" href="{{ url_for('product.haworthia', page=page_num) }}">{{ page_num }}</a>
              </li>
            {% endif %}
          {% else %}
          <li class="page-item me-2">...</li>
          {% endif %}
        {% endfor %}
      </ul>
      </nav>
    </div>
</section>

{% endblock %}

app/templates/product/product_card.html
<h1>
    Карточка товара {{product.name}}
    <p>
    <a href="{{ url_for('product.index', page=page_num) }}">Каталог</a>
    </p>
</h1>

app/templates/product/sortpricetest.html
{% for product in products %}

    <h5>{{ product.price }}</h5>

{% endfor %}

app/templates/slider.html
<section class="slider">
  {% if products.page == 1 %}
    <div
      id="carouselExampleIndicators"
      class="carousel slide"
      data-bs-ride="true"
    >
      <div class="carousel-indicators">
        <button
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide-to="0"
          class="active"
          aria-current="true"
          aria-label="Slide 1"
        ></button>
        <button
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide-to="1"
          aria-label="Slide 2"
        ></button>
        <button
          type="button"
          data-bs-target="#carouselExampleIndicators"
          data-bs-slide-to="2"
          aria-label="Slide 3"
        ></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{{url_for('static', filename='/img/slide-1.jpg')}}" class="d-block w-100" alt="..." />
        </div>
        <div class="carousel-item">
          <img src="{{url_for('static', filename='/img/slide-2.jpg')}}" class="d-block w-100" alt="..." />
        </div>
        <div class="carousel-item">
          <img src="{{url_for('static', filename='/img/slide-3.jpg')}}" class="d-block w-100" alt="..." />
        </div>
      </div>
      <button
        class="carousel-control-prev"
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button
        class="carousel-control-next"
        type="button"
        data-bs-target="#carouselExampleIndicators"
        data-bs-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    {% else %}
    <div class="container pt-5"></div>
    {% endif %}
  </section>